#ifndef GRAPHS_GETGROUP_GETNAME_GRAFO_DIRIGIDO_H
#define GRAPHS_GETGROUP_GETNAME_GRAFO_DIRIGIDO_H

#include "Grafo.cpp"

class Grafo_Dirigido : public Grafo{


};


#endif //GRAPHS_GETGROUP_GETNAME_GRAFO_DIRIGIDO_H
