#ifndef GRAPHS_GETGROUP_GETNAME_ARISTA_DIRIGIDA_H
#define GRAPHS_GETGROUP_GETNAME_ARISTA_DIRIGIDA_H

#include "Arista.cpp"

class Arista_dirigida: public Arista{

};


#endif //GRAPHS_GETGROUP_GETNAME_ARISTA_DIRIGIDA_H
