#ifndef GRAPHS_GETGROUP_GETNAME_ARISTA_NO_DIRIGIDA_H
#define GRAPHS_GETGROUP_GETNAME_ARISTA_NO_DIRIGIDA_H
#include "Arista.h"

class Arista_no_dirigida: public Arista {

};


#endif //GRAPHS_GETGROUP_GETNAME_ARISTA_NO_DIRIGIDA_H
